version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn InForm.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8000"
  hotloader:
    build:
      context: .
      dockerfile: docker/hotloader.Dockerfile
    container_name: hl01
    command: bash -c "npm install && npm start"
    volumes:
      - ./src:/src
    expose:
      - "3000"
    ports:
      - "3000:3000"